### ISSUE TITLE
V_drum Explorer does not detect TD-50 module

### ISSUE THREAD

**Issue by CarlDBaxter** [jskeet/DemoCode#119]
Dear jskeet

I'm looking forward to using your v-drum editor.

I am not sure if I am doing something wrong, but it does not detect my TD-50 module. I have tried the module in both VENDOR and GENERIC USB modes to see if that made a difference.

I attach images of the log. Github will not allow me to attach your log file export.

Best regards

Carl

![image](https://user-images.githubusercontent.com/69793077/90382068-2d5c2e00-e076-11ea-8ae4-0a3609dfa015.png)
![image](https://user-images.githubusercontent.com/69793077/90382127-3d740d80-e076-11ea-805d-644933e62576.png)

**Comment by jskeet** [comment]
That's very odd - I don't know why it wouldn't be able to "see" the TD-50. It's clearly taken a second to try to detect devices.

The VENDOR mode is the one you want, but I wonder if there's something in the MIDI setup. Looking at the TD-50 manual, in the "SETUP MENU 2" screen, if you press F1 for MIDI, the top option is "MIDI TX/RX Sw" - I suspect we need that to be "On". If that's already on, could you let me know what the other settings are on that screen? (The manual only shows the first 6 settings.)

**Comment by CarlDBaxter** [comment]
Hi,

Thanks for your ideas and responding promptly.

Unfortunately it did not work. I also tried changing USB sockets for the USB to the TD-50 module, and I disconnected the other midi devices to see if they were interfering - but no success.

The options on the midi screen are:

MIDI Tx/RX sw                ON
Midi Channel                 10
Programme Change Tx  ON
Programme Change Rx  ON
Soft Through Midi          OFF
Soft Through USB Midi   OFF
Local Control                   ON
Device ID                         17
Tx Edit Data                      ON
Receive Exclusive             OFF

Best regards

Carl

![image](https://user-images.githubusercontent.com/69793077/90438165-7ab6ba80-e0cb-11ea-922e-0ae88d843257.png)

**Comment by CarlDBaxter** [comment]
Oh, and it is in Vendor mode. I rebooted to make sure that the module was in that mode.

Many thanks

Carl

**Comment by jskeet** [comment]
Aha - "Receive exclusive" may well be the problem, as basically everything happens via System Exclusive (SysEx) messages. Try turning that on and give it another go :)

(If this works, I'll update the user guide...)

**Comment by CarlDBaxter** [comment]
Hi,

Yes, that worked, thank you!

"Receive Exclusive" had to be ON

I'm loading the module data now. May take some time, and looking forward to experimenting.

Many thanks!

Carl

**Comment by jskeet** [comment]
Hooray - very glad to hear it. I've updated the documentation to note that. (It turns out there's the same setting on the TD-17 and TD-27 too.)
