### ISSUE TITLE
"Copy node"

### ISSUE THREAD

**Issue by jskeet** [jskeet/DemoCode#123]
We can currently copy a kit from one place to another. It would be good to be able to copy any node (e.g. a single trigger) to a "similarly shaped" node.

We'd need to work out what this meant for other things, e.g. mfx and vedit, but it should be doable.

**Comment by W00PIE** [comment]
That would be awesome. The highend models have this feature and it is really frustrating, time-consuming and error-prone to manually recreate a snare from one kit in another.

**Comment by jskeet** [comment]
@W00PIE: Out of interest, would you want that to be "whole trigger", or just "trigger main instrument" vs "trigger sub instrument"? I don't know off-hand which would be easier from a code perspective. I expect it'll be worth explicitly creating some "copy points", i.e. nodes that offer a copy option, rather than trying to make it completely generalizable. (So it makes sense to be able to copy one MFX node to another in a TD-50 for example, or instruments... but not *every* node makes sense to copy.)

**Comment by W00PIE** [comment]
@jskeet I think I get your point... Copy and paste only makes sense when you copy from and paste to the same type, I guess. And sure, that would be sufficient: go to kit #XY, expand the nodes, right-click on "Snare Head", copy, go to kit #XY+n, right-click on "Snare Head" and paste.

**Comment by jskeet** [comment]
@W00PIE: That's part of my point, yes. The tricky question is whether the nodes are granular enough though - if "Copy Snare Head" copies all of:

- Main instrument + vedit
- Sub instrument + vedit
- Common parts (pan, min/max volume, eq etc)

... is that okay, or would you want to be able to copy/paste *just* the main instrument (with vedit, I assume). Here's a funky idea: is copying the main instrument for one trigger as the sub instrument for a different trigger (whether on the same kit or not) a useful notion?

I suspect I can go with "copy a single node from the LHS" first (working out the actual UI might be "interesting", but I can come to that later) to start with, which will be the simple "Copy the whole of the Snare Head trigger" - we can work out the aspects for more fine-grained copying later, if anyone asks.

**Comment by W00PIE** [comment]
@jskeet I'd be totally happy with a simple "copy/paste that node with everything in it" to a node of the same type. Sure, you can think of a more sophisticated mechanism that lets you choose what exactly you want to take from a node and everything below, but that is probably a lot of UI work. From a drummers perspective, I don't need it.

**Comment by jskeet** [comment]
Good news - I've managed to implement this relatively easily. It's somewhat ugly at the moment - just "Copy node" and "Paste node" buttons, with a label to show the path of what you've copied, but it seems to work (and allows you to copy anything "sensible" - copy a trigger from one kit to another, or to elsewhere in the same kit, copy MFX, copy a trigger bank etc). I'm seeing whether I can fix the TD-50X issues, then I'll do a release. I may not have time to update the documentation for a while, but hopefully it'll be intuitive enough...

**Comment by jskeet** [comment]
I've just released 1.0.0-alpha11 - ([download](https://github.com/jskeet/DemoCode/releases/download/VDrumExplorer-1.0.0-alpha11/VDrumExplorer-Setup-1.0.0-alpha11.msi)) which has this functionality. Please let me know how you get on with it. As I said before, the UI is pretty crude at the moment, but it's functional. 

I'll update docs when I get the chance, but that may not be for a little while.

**Comment by jskeet** [comment]
Closing as this is now done.
