### ISSUE TITLE
Semaphore not released in CamController

### ISSUE THREAD

**Issue by Soon5** [jskeet/DemoCode#131]
Hello,

Thanks for the Demo VISCA Code. I used it and found a bug:

In ViscaClientBase IViscaClient.SendAsync(ViscaPacket request, CancellationToken cancellationToken)

at the end, before the semaphore is released, you do a reconnect. If the reconnect fails with an Exception, the semaphore is never released and therefore the Code is in a deadlock, forever... Add another try / finally and you are good.

Cheers

**Comment by jskeet** [comment]
Thanks, I'll have a look when I get a chance.

**Comment by jskeet** [comment]
Fixed now, thanks.
