### ISSUE TITLE
Convert TD50 to TD50x

### ISSUE THREAD

**Issue by Sommi486** [jskeet/DemoCode#140]
Will there be an option to convert our custom kits from TD50 to the new TD50x format?

**Comment by jskeet** [comment]
This is the first I've heard of the TD50X to be honest.

I don't have much time to work on V-Drum Explorer at the moment... so even supporting the TD50X at all will take a while (it takes a long time to sort out the schema, which may end up being fairly different from the TD50). In terms of converting kits... if the schemas are similar enough, it *might* be feasible... I'd have to look into it in a lot more detail though.

**Comment by jskeet** [comment]
Okay, there's now a release with somewhat-experimental TD-50X support... but I'm afraid I think that converting between kits is going to be more work than I have time for. It would be feasible, but I just don't have time :(
