### ISSUE TITLE
Communication problem after upgrade TD50 -> TD50X

### ISSUE THREAD

**Issue by DrumCoca45** [jskeet/DemoCode#147]
Dear  jskeet.

First , I'm french so sorry for my "bad english" 

Congratulations for your very good job . I've tested the last version of VdrumExplorer (alpha10) with my TD50 . Everything OK .
Yesterday, I upgrade the firmware to TD50X and try again . New module is connected but loading data is impossible.

![image](https://user-images.githubusercontent.com/93822286/140619762-dd6b117d-6b6a-4741-b83d-1e31d780881a.png)

The options on the midi screen are:
MIDI Tx/RX sw ON
Midi Channel 10
Programme Change Tx ON
Programme Change Rx ON
Soft Through Midi OFF
Soft Through USB Midi OFF
Local Control ON
Device ID 17
Tx Edit Data ON
Receive Exclusive ON

The driver is correctly loaded and DRIVER MODE is VENDOR on TD50X

Have your an idea to resolve this problem ?

Best regards

Bruno

**Comment by jskeet** [comment]
Yes, unfortunately I've heard the same from another user by email. I've sent him a diagnostic tool that will hopefully give me more information - I'm hoping that I'll have something working in a week or so, unless it proves completely different to other modules. Stay tuned, basically - I'll add another comment when I have more info.

**Comment by DrumCoca45** [comment]
Thanks for your answer . 
I think you're right and TD50 upgraded isn't exactly the same module that a TD50X . 
 
Good luck and thanks a lot
Bruno

**Comment by jskeet** [comment]
Oh it's definitely not the same - the schema AHAs significant differences to the TD-50. I'd hoped the communication protocol would be the same, but it looks like there are subtle differences. I'm sure we'll get there.

**Comment by DrumCoca45** [comment]
Ok
I do not master the C + language but I have been a computer technician since 1980 and I know some protocols and other technical fields. So , If I can help you with testing, don't hesitate to ask me

**Comment by jskeet** [comment]
I've just released 1.0.0-alpha11 - ([download](https://github.com/jskeet/DemoCode/releases/download/VDrumExplorer-1.0.0-alpha11/VDrumExplorer-Setup-1.0.0-alpha11.msi)) which should be much better. There may still be some schema issues, so please back up all your data on the module before you start copying any data back to it from the V-Drum Explorer (just loading it *into* V-Drum Explorer should be safe). I'll close this issue now, but if you still have problems with it, please just add a comment and I'll reopen.

**Comment by DrumCoca45** [comment]
I tested the new release .  Communication is operational . Sending and receiving data;kits and node is working.
Thanks a lot for your very good job .

**Comment by jskeet** [comment]
Hooray! Glad to hear it's working for you.
