### ISSUE TITLE
Trigger recognition

### ISSUE THREAD

**Issue by W00PIE** [jskeet/DemoCode#148]
I noticed that on my TD17-KVX (with some custom pads) that the recognized triggers differ from what I see in the module. Here's an overview of what I have configured in the TD17 and what the Module Explorer shows:

```
[TD17]           [Module Explorer]
Kick: KD10   --> KD85
Snare: PD125 --> PAD100L
Tom1: PDX8   --> PD85
Tom2: PDX8   --> PD85
Tom3: PDX12  --> PD105
HH: VH10     --> PDX6
Crash1: CY8  --> CY14CT
Crash2: CY8  --> CY14CT
Ride: CY15R  --> PD8
Aux: CY8     --> CY14CT
```

**Comment by jskeet** [comment]
Thanks for the report - I'll check the schema details. Please could you let me know which version of the TD-17 firmware you're using? If Roland has added a pad within the list, that would put everything slightly out of whack. (And I suspect the best I'll be able to do is say "for any given release, it's correct for the latest firmware" - assuming the Roland documentation is kept up-to-date too.)

**Comment by jskeet** [comment]
Okay - it looks like you've probably got the firmware that goes with the MIDI implementation document 1.00 (May 2018). V-Drum Explorer has been updated to the pads in document 1.01 (Jan 2019). So I think if you update to the latest firmware, it *should* be correct.

**Comment by W00PIE** [comment]
You're right, and that's strange: I am sure that I updated the firmware to 1.02 when I bought the kit last november, maybe a factory reset not only wipes the user settings but also downgrades the firmware? Whatever, I just ran through a firmware update, just to be safe, and I am on version 1.02 (0026) now. I configured my pads and cymbals and now I everything gets recognized correctly in the Module Explorer. Thanks alot!

Content of the log file:
```
[
  {
    "timestamp": "2021-11-08T18:38:32.1412339Z",
    "level": "Information",
    "message": "V-Drum Explorer version 1.0.0-alpha10"
  },
  {
    "timestamp": "2021-11-08T18:38:32.4201859Z",
    "level": "Information",
    "message": "Input device: 'TD-17'"
  },
  {
    "timestamp": "2021-11-08T18:38:32.4222358Z",
    "level": "Information",
    "message": "Output device: 'Microsoft GS Wavetable Synth'"
  },
  {
    "timestamp": "2021-11-08T18:38:32.4222358Z",
    "level": "Information",
    "message": "Output device: 'TD-17'"
  },
  {
    "timestamp": "2021-11-08T18:38:32.4222358Z",
    "level": "Information",
    "message": "Detecting devices for MIDI ports with name 'TD-17'"
  },
  {
    "timestamp": "2021-11-08T18:38:33.459718Z",
    "level": "Information",
    "message": "  Detected single Roland device identity: 17: Roland product 843/0, revision 16777216"
  },
  {
    "timestamp": "2021-11-08T18:38:33.459718Z",
    "level": "Information",
    "message": "  Identity matches known schema 'TD-17'."
  }
]
```
