### ISSUE TITLE
Link to TD-17 Midi implementation not working

### ISSUE THREAD

**Issue by MartijnZ** [jskeet/DemoCode#167]
Hi JSKeet,

Nice work on the Roland V-Drum Explorer! Looks like a very nice project :).

I recently upgraded my kit from TD-9 to TD-17. Although the new module is great, it lacks the ability to visually validate your timing as the TD-9 did. This activated my nerd-drive and try to recreate timing visualizer over Midi.  

Googling around for V-Drum Midi implementation I stumbled on your git repo. Although it contains a link to Roland's implementation, the link does not seem to work anymore. I guess you want to point to this file:
https://static.roland.com/assets/media/pdf/TD-17_MIDI_Imple_eng01_W.pdf

Again nice work on the V-Drums explorer, I guess I'll have a peek at the code to get my Python drum timing visualizer to work.

Happy holidays,

Martijn

**Comment by jskeet** [comment]
There's a new firmware version and thus a new midi document. I'll update the page when I get a chance.

**Comment by jskeet** [comment]
Thanks, I've now fixed the doc.
