### ISSUE TITLE
Love this program!...Just needed to pass on an error in my log regarding 'invalid raw value' (click for full log)...

### ISSUE THREAD

**Issue by DiscoFever78** [jskeet/DemoCode#173]
Log: 
V-Drum Explorer version 1.0.0-alpha13 
Input device: 'TD-17' 
Output device: 'Microsoft GS Wavetable Synth' 
Output device: 'TD-17' 
Detecting devices for MIDI ports with name 'TD-17' 
  Detected single Roland device identity: 17: Roland product 843/0, revision 2 
  Identity matches known schema 'TD-17'. 
Invalid raw value 39 (path: /Kit[12]/KitMfx/Type) 
Invalid raw value 47 (path: /Kit[12]/KitMfx/Parameters/{Delay}/DelayLeftSync) 
Invalid raw value 40 (path: /Kit[12]/KitMfx/Parameters/{Delay}/PhaseLeft) 
Invalid raw value 79 (path: /Kit[12]/KitMfx/Parameters/{Delay}/PhaseRight) 
Invalid raw value 50 (path: /Kit[12]/KitMfx/Parameters/{Delay}/FeedbackMode) 
Invalid raw value 127 (path: /Kit[12]/KitMfx/Parameters/{Delay}/Feedback) 
Invalid raw value 300 (path: /Kit[12]/KitMfx/Parameters/{Delay}/HighFrequencyDamp) 
Invalid raw value 59 (path: /Kit[12]/KitMfx/Parameters/{Delay}/HighGain) 

-Thanks, and my apologies if this has already been reported.

**Comment by jskeet** [comment]
Ooh, that's interesting. I assume you've got the newest firmware... it looks like another 11 MFX types were added to the TD-17 (but *not* the TD-27 yet, interestingly): "EQUALIZER, SPECTRUM, LOW BOOST, ENHANCER, HUMANIZER, SLICER, STEP FLANGER, HEXA-CHORUS, 4 TAP PAN DELAY, EH->FLANGER, SPEAKER SIM".

Thanks very much for reporting this. I'll add those to the schema as soon as I can - it may be a week or two, but I'll update this issue when I'm done. Unfortunately I won't easily be able to test it, and transcribing the schema can be a slightly error-prone process, so please do report any other problems when it's done. (Hopefully they'll be minor.)

**Comment by jskeet** [comment]
Have now added these to the source code - will check with the TD-17 at church this weekend, and do a release shortly afterwards if all looks good.

**Comment by jskeet** [comment]
Done - this is now available in 1.0.0-alpha14, available from the release page: https://github.com/jskeet/DemoCode/releases/tag/VDrumExplorer-1.0.0-alpha14

Please feel free to reopen this issue if you encounter any more problems.

**Comment by DiscoFever78** [comment]
Thanks so much!! This is perfect for my 'V2' module. -Again, love this software!

**Comment by DiscoFever78** [comment]
Just an update: I installed the new release and it works great!!... (I also slightly modified the title of this GitHub posting, as my O.C.D. was at work again, lol)... Cheers!

**Comment by jskeet** [comment]
Hooray - really glad to hear that :)
