### ISSUE TITLE
TD-17 copy v1 data to v2 issue

### ISSUE THREAD

**Issue by jeblomberg** [jskeet/DemoCode#174]
If I load a file created/saved from the v1 version of the TD-17,  I can't copy kits to my upgraded v2 TD-17.  Is there a way to 'upgrade' a patch from v1 to v2?

**Comment by jskeet** [comment]
No, I'm afraid not. I could *potentially* try to write per-module update code, but it would be very time-consuming (for a project I don't have very much time for at the moment) and potentially quite brittle.

I'll *think* about whether there's some hacky way of doing thing by adding a JSON format or something similar to serialize the data out and then parse it back again... but it's unlikely I'll get to it any time soon, I'm afraid.

**Comment by jskeet** [comment]
Some progress: I've created a small tool to format the data as JSON. Parsing it will be more challenging, but we'll see how that comes along...

**Comment by jskeet** [comment]
Good news! This is basically implemented now. I want to wait until the weekend before releasing so that I can check the default values for the new TD-17 v2 MFX overlays, but I should be able to release soon.

**Comment by jskeet** [comment]
Done - this is now available in 1.0.0-alpha14, available from the release page: https://github.com/jskeet/DemoCode/releases/tag/VDrumExplorer-1.0.0-alpha14

Basically, open up an existing module/kit file, and in the File menu there'll be a "Convert to" option if there's more than one firmware version for that data's device.
Note that it *does* allow you to go "backwards", but I don't vouch for the results of that - and you'll find the UI hangs for a long time when trying it, as it's writing thousands of log entries for invalid fields. It gets there eventually though...

**Comment by jeblomberg** [comment]
Incredible.  Thank you!
