### ISSUE TITLE
Sonos Controller

### ISSUE THREAD

**Issue by ReiVaX1508** [jskeet/DemoCode#18]
Hi;

I work on you're Sonos controller for my home; before my question...it's beatifull work and i learn all the code for understand that.
Sorry for my english; i'm french;

My test worked; but i tried to get the state of volume and current track's name with UPNP syntax.
But doesn't work. Can you help me to successfull that ??

```
        [Description("Get current volume")]
        public void GetVolume(int percentVolume)
        {
            SendCommand(RenderingControlPath,
                new XElement(RenderingControlNs + "GetVolume",
                    Instance0,
                    new XElement("Channel", "Master"),
                    new XElement("CurrentVolume", percentVolume)));
        }
```

**Comment by jskeet** [comment]
I'm afraid I don't think I ever tried to do that - the commands I wrote are all "one way" effectively rather than retrieving information. Sorry not to be able to be of more assistance! (I'd offer to investigate it myself, but I just don't have time at the moment...)
