### ISSUE TITLE
New Feature Request: Add Save to File capability

### ISSUE THREAD

**Issue by mslinn** [jskeet/DemoCode#182]
Once data is read from a drum sound module, it would be helpful to be able to save that data to a local file on the computer.

**Comment by jskeet** [comment]
You already can do that - that's what the File menu is for.

**Comment by mslinn** [comment]
Where is that?

https://mslinn.com/av_studio/760-vdrum-explorer.html

**Comment by jskeet** [comment]
Top left of various of the screenshots on that page.

There's only one title per window type - but "kit explorer" explores a single kit, and "module explorer" explores a whole module. They're very similar, but the kit explorer is scoped to a single kit within a module.

**Comment by mslinn** [comment]
I do not see a menu in any window. Is there a menu in the following window, which is the first image in the article?

![v-drum_explorer-1](https://github.com/user-attachments/assets/ca8dd606-17c0-4b72-8f82-d14d6c708151)

The **Load file** button can read a file, but I want to write a file.

I see a pull-down widget that allows me to select a schema, and another pull-down widget for log level. Neither of them appear to have anything to do with export or write capability.

**Comment by jskeet** [comment]
In the Module Explorer window, just below the title, there's a File menu - it's shown in your screenshots.

**Comment by jskeet** [comment]
(Likewise in Kit Explorer.)

**Comment by mslinn** [comment]
Super, I have updated the article with what I currently know.

Right now, I see 2 identical Kit Explorers, a Schema Explorer, and a V-Drum Explorer Home window. Would you please explain what each window does, and how they are created? I would add your words to the article.

**Comment by jskeet** [comment]
Not sure what you mean by "how they are created". The home is really just a launchpad for the other windows. Schema explorer is for - well, exploring the schema of the module (as opposed to the data within any specific physical module) - so you can see what fields are available etc. (It's probably more use to me than to mainstream users, but it does allow you to compare the functionality between different modules to some extent.)
