### ISSUE TITLE
Not an issue, but rather a question

### ISSUE THREAD

**Issue by IEvangelist** [jskeet/DemoCode#6]
Hi Jon,

I'm confused by what you're trying to demonstrate with [this bit of code](https://github.com/jskeet/DemoCode/blob/master/CSharp7/CSharp7/AsyncReturn.cs#L16-L102) - please do enlighten me. I have forked your code and it seems as though the value of `10` is never actually returned, but instead the value of `0`. I was anticipating "After Await" to be logged to the console - I'm certain there is a corresponding explanation... please do tell.

Thank you

**Comment by jskeet** [comment]
This is just demonstrating how that it compiles - it's not a fully-functional task by any means.

It completes immediately because `IsCompleted` returns true - we're never doing any of the work to actually fire continuatoins etc.
