### ISSUE TITLE
Record instruments issue

### ISSUE THREAD

**Issue by 8thnotepete** [jskeet/DemoCode#92]
When recording instruments, only a kick sound is recorded. It is the same sound (kick) for all instruments.
Setup details:
TD-27 module
Instrument group to record: Snare or All; the same results for both.
Input device: MASTER (TD-27) or KICK (TD-27)
Kit to use: 100; same results on other kits.
Attack: 80

I can hear kick sound being generated by the module in the headphones connected to it.
Recorded file contains correct number of instruments, i.e. 28 for snare group however, each has the same (kick) sound.

**Comment by jskeet** [comment]
Did you put the module on kit 100 before starting? That's the kit that it's changing the instrument for. It's deliberately playing the kick each time, but changing the instrument associated with the kick between each note.

At some point I'll fix it to set the current kit automatically at the start...

**Comment by 8thnotepete** [comment]
I have missed that - sorry. When I dial-in kit #100 all sounds are being played correctly.

**Comment by jskeet** [comment]
Hooray! If you have any suggestions for making it clearer in the documentation before I get round to making that step redundant, please let me know :)
