### ISSUE TITLE
Not finding correct TD-17 MIDI ports

### ISSUE THREAD

**Issue by jeblomberg** [jskeet/DemoCode#97]
I have multiple MIDI devices on my PC.  There doesn't seem to be a way to detect or enter the correct MIDI port in the config file.  The code looks like it's trying to find the name based on a sorted list? (MidiDevices.cs lines 80-90)

Log:

15:57:54.153 V-Drum Explorer version 1.0.0-alpha04
15:57:54.265 Detecting MIDI ports
15:57:54.265 Input ports:
15:57:54.265 0: 2- TD-17 ()
15:57:54.265 1: TASCAM US-1800 MIDI ()
15:57:54.265 Output ports:
15:57:54.265 0: Microsoft GS Wavetable Synth ()
15:57:54.265 1: 2- TD-17 ()
15:57:54.265 2: TASCAM US-1800 MIDI ()
15:57:54.266 Detected multiple input/output MIDI ports: 2- TD-17,TASCAM US-1800 MIDI. Abandoning MIDI detection.
15:57:54.268 -----------------
15:57:54.269 Loading known schemas
15:57:54.269 Loading schema for TD-17
15:57:54.652 Loading schema for TD-27
15:57:54.796 Loading schema for TD-50
15:57:54.981 Finished loading schemas

**Comment by jskeet** [comment]
Currently it expects there to be a single input/output pair with the same name - in your case you have two of them.

For the purposes of checking everything else, are you able to unplug the TASCAM US-1800 while using V-Drum Explorer? I can try to tighten this up for the next version. (I'm working on a complete rewrite, but this part of the code is basically the same at the moment.)

It's likely to take a bit longer to detect things if it's got multiple ports to check though.

**Comment by jskeet** [comment]
It looks like it should actually be pretty simple to do. How much of a blocker is this for you? (If you're using V-Drum Explorer for anything significant and this is really annoying, I can fix it this week and do another release. If this was more of a "this is an irritation; if it could be fixed at some point in the future that would be nice" then I'll probably fix it in the code next weekend, but not do a release until I'd be doing one anyway.)

**Comment by jeblomberg** [comment]
Yes, it works fine by unplugging the TASCAM, but that's basically my "sound card" (ADA converter + MIDI).  Is your re-write also in C#?

**Comment by jskeet** [comment]
Yup, the rewrite is basically trying to put a better architecture in place for WPF. I've started committing quite a bit of it back to GitHub already - it's still in https://github.com/jskeet/DemoCode/tree/master/Drums; the new code is in the projects ending with ".Model", ".ViewModel" and ".Gui". It's a fair way from having feature parity with the current alpha, but it's coming on.

Are you in a position to build and use the "old" code (in VDrumExplorer.Wpf) if I commit the fix? It's releasing that's relatively time-consuming.

**Comment by jeblomberg** [comment]
I'm not set up for C# nor have any experience in it (other than it's pretty close to Java).  I develop mostly in Java...so I was going to offer help if you were changing to Java.  No worries.  No rush.  I have that work-around that's just fine.  Thanks!

**Comment by jskeet** [comment]
Right, the code is in. I'll try to do a 1.0.0-alpha05 release over the weekend.

**Comment by jskeet** [comment]
I've just released 1.0.0-alpha05 - sorry for the delay! Download it from the releases page: https://github.com/jskeet/DemoCode/releases

**Comment by jeblomberg** [comment]
Awesome!  Thank you so much!  So much more fun to edit sounds this way!
